spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: uki
    password: 1123
  sql:
    init:
      mode: always
#      schema-locations: classpath:h2/schema.sql
      data-locations: classpath:h2/data.sql
  jackson:
    serialization:
        fail-on-empty-beans: false
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /uki-console
      settings:
        trace: false
        web-allow-others: true

aws:
  region: ap-northeast-2


cloud:
  aws:
    credentials:
      instanceProfile: true