
name: Deploy Spring boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: java11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials        #aws credentials 생성
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}    #secrets 변수 사용
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://notx2wice-puzzle/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name puzzle-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name prd --s3-location bucket=notx2wice-puzzle,bundleType=zip,key=$GITHUB_SHA.zip

#      CodeDeploy 에러 목록
#      1. Missing credentials
#      에러 메시지:
#        InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Missing credentials - please check if this instance was started with an IAM instance profile
#
#
#      해당 에러가 발생하게 된 원인은 아래와 같다.
#
#      1.  IAM 역할을 지정하지 않고 인스턴스를 실행시킨다.
#
#      2. 이후 실행시킨 인스턴스에 CodeDeploy Agent를 설치 한다.
#
#      3. 이때 설치된 CodeDeploy에는 해당 역할을 실행 할 수 있는 자격증명이 없기에 위와 같은 에러가 발생 하는 것 입니다.